// <auto-generated />
using System;
using AppGM.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppGM.Core.Migrations
{
    [DbContext(typeof(RolContext))]
    [Migration("20210530001644_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("AppGM.Core.ModeloAccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("AppGM.Core.ModeloAdministradorDeCombate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndicePersonajeTurnoActual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<uint>("TurnoActual")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Combates");
                });

            modelBuilder.Entity("AppGM.Core.ModeloAlianza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsVigente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModeloAlianza");
                });

            modelBuilder.Entity("AppGM.Core.ModeloCaracteristicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EArquetipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EManoDominante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ESexo")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Estatura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fisico")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Peso")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModeloCaracteristicas");
                });

            modelBuilder.Entity("AppGM.Core.ModeloCargas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CargasActuales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CargasMaximas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModeloCargas");
                });

            modelBuilder.Entity("AppGM.Core.ModeloContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsVigente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModeloContrato");
                });

            modelBuilder.Entity("AppGM.Core.ModeloDatosInvocacionBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModeloDatosInvocacionBase");
                });

            modelBuilder.Entity("AppGM.Core.ModeloEfecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaSiendoAplicado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<ushort>("TurnosDeDuracion")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("TurnosRestantes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModeloEfecto");
                });

            modelBuilder.Entity("AppGM.Core.ModeloHabilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CostoDeMana")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CostoDeOdOPrana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rango")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDeHabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("TurnosDeDuracion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModeloHabilidad");

                    b.HasDiscriminator<int>("Tipo").HasValue(1);
                });

            modelBuilder.Entity("AppGM.Core.ModeloLimitador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasDeEnfriamiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasRestantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteDeUsos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsosRestantes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModeloLimitador");
                });

            modelBuilder.Entity("AppGM.Core.ModeloMapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EFormatoImagen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreMapa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mapas");
                });

            modelBuilder.Entity("AppGM.Core.ModeloModificadorDeStatBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorRequeridoTirada")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModeloModificadorDeStatBase");

                    b.HasDiscriminator<int>("Tipo").HasValue(1);
                });

            modelBuilder.Entity("AppGM.Core.ModeloParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsSuTurno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiradaIniciativa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("AppGM.Core.ModeloPersonaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("End")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaEnCombate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormatoImagen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathImagen")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoCargado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoMaximoCargable")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PosicionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Str")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentajaAgi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentajaEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentajaInt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentajaLck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentajaStr")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PosicionId");

                    b.ToTable("ModeloPersonaje");

                    b.HasDiscriminator<int>("Clase").HasValue(3);
                });

            modelBuilder.Entity("AppGM.Core.ModeloRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Dia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaUltimaSesion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Registros")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("AppGM.Core.ModeloSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EspacioDisponible")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EspacioTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModeloSlot");
                });

            modelBuilder.Entity("AppGM.Core.ModeloTiradaBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModeloTiradaBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ModeloTiradaBase");
                });

            modelBuilder.Entity("AppGM.Core.ModeloUnidadMapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ETipoUnidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMapa");

                    b.HasDiscriminator<int>("Tipo").HasValue(1);
                });

            modelBuilder.Entity("AppGM.Core.ModeloUtilizable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EStatDeLaQueDepende")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EStatQueAfecta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModeloUtilizable");

                    b.HasDiscriminator<int>("Tipo").HasValue(1);
                });

            modelBuilder.Entity("AppGM.Core.ModeloVector2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Vectores2");
                });

            modelBuilder.Entity("AppGM.Core.TIAdministradorDeCombateMapa", b =>
                {
                    b.Property<int>("IdAdministradorDeCombate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMapa")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAdministradorDeCombate", "IdMapa");

                    b.HasIndex("IdMapa");

                    b.ToTable("CombateMapas");
                });

            modelBuilder.Entity("AppGM.Core.TIAdministradorDeCombateParticipante", b =>
                {
                    b.Property<int>("IdAdministradorDeCombate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdParticipante")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAdministradorDeCombate", "IdParticipante");

                    b.HasIndex("IdParticipante")
                        .IsUnique();

                    b.ToTable("CombateParticipantes");
                });

            modelBuilder.Entity("AppGM.Core.TIAlianzaContrato", b =>
                {
                    b.Property<int>("IdAlianza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdContrato")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAlianza", "IdContrato");

                    b.HasIndex("IdAlianza")
                        .IsUnique();

                    b.HasIndex("IdContrato");

                    b.ToTable("TIAlianzaContrato");
                });

            modelBuilder.Entity("AppGM.Core.TIArmasDistanciaEfecto", b =>
                {
                    b.Property<int>("IdArmasDistancia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEfecto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdArmasDistancia", "IdEfecto");

                    b.HasIndex("IdEfecto");

                    b.ToTable("TIArmasDistanciaEfecto");
                });

            modelBuilder.Entity("AppGM.Core.TIArmasDistanciaTiradaDeDaño", b =>
                {
                    b.Property<int>("IdArmasDistancia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTirada")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdArmasDistancia", "IdTirada");

                    b.HasIndex("IdArmasDistancia")
                        .IsUnique();

                    b.HasIndex("IdTirada");

                    b.ToTable("TIArmasDistanciaTiradaDeDaño");
                });

            modelBuilder.Entity("AppGM.Core.TIArmasDistanciaTiradaVariable", b =>
                {
                    b.Property<int>("IdArmasDistancia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTirada")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdArmasDistancia", "IdTirada");

                    b.HasIndex("IdArmasDistancia")
                        .IsUnique();

                    b.HasIndex("IdTirada");

                    b.ToTable("TIArmasDistanciaTiradaVariable");
                });

            modelBuilder.Entity("AppGM.Core.TIEfectoModificadorDeStatBase", b =>
                {
                    b.Property<int>("IdEfecto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdModificadorDeStat")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEfecto", "IdModificadorDeStat");

                    b.HasIndex("IdModificadorDeStat");

                    b.ToTable("TIEfectoModificadorDeStatBase");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadCargasHabilidad", b =>
                {
                    b.Property<int>("IdHabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCargasHabilidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHabilidad", "IdCargasHabilidad");

                    b.HasIndex("IdCargasHabilidad");

                    b.HasIndex("IdHabilidad")
                        .IsUnique();

                    b.ToTable("TIHabilidadCargasHabilidad");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadEfecto", b =>
                {
                    b.Property<int>("IdHabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEfecto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHabilidad", "IdEfecto");

                    b.HasIndex("IdEfecto");

                    b.ToTable("TIHabilidadEfecto");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadInvocacion", b =>
                {
                    b.Property<int>("IdHabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdInvocacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHabilidad", "IdInvocacion");

                    b.HasIndex("IdInvocacion");

                    b.ToTable("TIHabilidadInvocacion");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadItem", b =>
                {
                    b.Property<int>("IdHabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHabilidad", "IdItem");

                    b.HasIndex("IdItem");

                    b.ToTable("TIHabilidadItem");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadLimitador", b =>
                {
                    b.Property<int>("IdHabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdLimitador")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHabilidad", "IdLimitador");

                    b.HasIndex("IdHabilidad")
                        .IsUnique();

                    b.HasIndex("IdLimitador");

                    b.ToTable("TIHabilidadLimitador");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadTiradaBase", b =>
                {
                    b.Property<int>("IdHabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTirada")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHabilidad", "IdTirada");

                    b.HasIndex("IdTirada");

                    b.ToTable("TIHabilidadTiradaBase");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadTiradaDeDaño", b =>
                {
                    b.Property<int>("IdHabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTirada")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHabilidad", "IdTirada");

                    b.HasIndex("IdHabilidad")
                        .IsUnique();

                    b.HasIndex("IdTirada");

                    b.ToTable("TIHabilidadTiradaDeDaño");
                });

            modelBuilder.Entity("AppGM.Core.TIInvocacionDatosInvocacion", b =>
                {
                    b.Property<int>("IdInvocacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDatos")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdInvocacion", "IdDatos");

                    b.HasIndex("IdDatos");

                    b.HasIndex("IdInvocacion")
                        .IsUnique();

                    b.ToTable("TIInvocacionDatosInvocacion");
                });

            modelBuilder.Entity("AppGM.Core.TIInvocacionEfecto", b =>
                {
                    b.Property<int>("IdInvocacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEfecto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdInvocacion", "IdEfecto");

                    b.HasIndex("IdEfecto");

                    b.HasIndex("IdInvocacion")
                        .IsUnique();

                    b.ToTable("TIInvocacionEfecto");
                });

            modelBuilder.Entity("AppGM.Core.TIInvocacionPersonaje", b =>
                {
                    b.Property<int>("IdInvocacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdInvocacion", "IdPersonaje");

                    b.HasIndex("IdInvocacion")
                        .IsUnique();

                    b.HasIndex("IdPersonaje");

                    b.ToTable("TIInvocacionPersonaje");
                });

            modelBuilder.Entity("AppGM.Core.TIMapaUnidadMapa", b =>
                {
                    b.Property<int>("IdMapa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnidadMapa")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMapa", "IdUnidadMapa");

                    b.HasIndex("IdUnidadMapa");

                    b.ToTable("MapasUnidadesMapa");
                });

            modelBuilder.Entity("AppGM.Core.TIModificadorDeStatBaseTiradaBase", b =>
                {
                    b.Property<int>("IdModificadorDeStatBase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTirada")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdModificadorDeStatBase", "IdTirada");

                    b.HasIndex("IdModificadorDeStatBase")
                        .IsUnique();

                    b.HasIndex("IdTirada");

                    b.ToTable("TIModificadorDeStatBaseTiradaBase");
                });

            modelBuilder.Entity("AppGM.Core.TIOfensivoEfecto", b =>
                {
                    b.Property<int>("IdOfensivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEfecto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdOfensivo", "IdEfecto");

                    b.HasIndex("IdEfecto");

                    b.HasIndex("IdOfensivo")
                        .IsUnique();

                    b.ToTable("TIOfensivoEfecto");
                });

            modelBuilder.Entity("AppGM.Core.TIOfensivoTiradaDeDaño", b =>
                {
                    b.Property<int>("IdOfensivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTiradaDeDaño")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdOfensivo", "IdTiradaDeDaño");

                    b.HasIndex("IdTiradaDeDaño");

                    b.ToTable("TIOfensivoTiradaDeDaño");
                });

            modelBuilder.Entity("AppGM.Core.TIParticipanteAccion", b =>
                {
                    b.Property<int>("IdParticipante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAccion")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdParticipante", "IdAccion");

                    b.HasIndex("IdAccion");

                    b.ToTable("ParticipanteAccion");
                });

            modelBuilder.Entity("AppGM.Core.TIParticipantePersonaje", b =>
                {
                    b.Property<int>("IdParticipante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdParticipante", "IdPersonaje");

                    b.HasIndex("IdParticipante")
                        .IsUnique();

                    b.HasIndex("IdPersonaje");

                    b.ToTable("ParticipantePersonaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeAlianza", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAlianza")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdAlianza");

                    b.HasIndex("IdAlianza");

                    b.ToTable("PersonajeAlianzas");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeArmaDistancia", b =>
                {
                    b.Property<int>("IdArmaDistancia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdArmaDistancia", "IdPersonaje");

                    b.HasIndex("IdPersonaje");

                    b.ToTable("PersonajeArmasDistancias");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeContrato", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdContrato")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdContrato");

                    b.HasIndex("IdContrato");

                    b.ToTable("PersonajeContratos");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeDefensivo", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDefensivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdDefensivo");

                    b.HasIndex("IdDefensivo");

                    b.ToTable("PersonajeDefensivos");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeEfecto", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEfecto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdEfecto");

                    b.HasIndex("IdEfecto");

                    b.ToTable("PersonajeEfectos");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeHabilidad", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdHabilidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdHabilidad");

                    b.HasIndex("IdHabilidad");

                    b.ToTable("PersonajeSkills");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeJugableCaracteristicas", b =>
                {
                    b.Property<int>("IdPersonajeJugable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCaracteristica")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonajeJugable", "IdCaracteristica");

                    b.HasIndex("IdCaracteristica");

                    b.HasIndex("IdPersonajeJugable")
                        .IsUnique();

                    b.ToTable("TIPersonajeJugableCaracteristicas");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeJugableInvocacion", b =>
                {
                    b.Property<int>("IdPersonajeJugable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdInvocacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonajeJugable", "IdInvocacion");

                    b.HasIndex("IdInvocacion");

                    b.ToTable("TIPersonajeJugableInvocacion");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeMagia", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMagia")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdMagia");

                    b.HasIndex("IdMagia");

                    b.ToTable("PersonajeMagias");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeModificadorDeDefensa", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdModificadorDefensa")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdModificadorDefensa");

                    b.HasIndex("IdModificadorDefensa");

                    b.ToTable("PersonajeModificadoresDeDefensa");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajePerk", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPerk")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdPerk");

                    b.HasIndex("IdPerk");

                    b.ToTable("PersonajePerks");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeUnidadMapa", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnidadMapa")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdUnidadMapa");

                    b.HasIndex("IdUnidadMapa")
                        .IsUnique();

                    b.ToTable("PersonajesUnidadesMapa");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeUtilizable", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUtilizable")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPersonaje", "IdUtilizable");

                    b.HasIndex("IdUtilizable");

                    b.ToTable("PersonajeUtilizables");
                });

            modelBuilder.Entity("AppGM.Core.TIPortableModificadorDeStatBase", b =>
                {
                    b.Property<int>("IdPortable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdModificadorDeStat")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPortable", "IdModificadorDeStat");

                    b.HasIndex("IdModificadorDeStat");

                    b.ToTable("TIPortableModificadorDeStatBase");
                });

            modelBuilder.Entity("AppGM.Core.TIPortableSlots", b =>
                {
                    b.Property<int>("IdPortable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSlot")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPortable", "IdSlot");

                    b.HasIndex("IdSlot");

                    b.ToTable("TIPortableSlots");
                });

            modelBuilder.Entity("AppGM.Core.TIRolCombate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCombate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModeloAdministradorDeCombateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeloRolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeloRolId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCombate")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.HasIndex("ModeloAdministradorDeCombateId");

                    b.HasIndex("ModeloRolId1");

                    b.ToTable("CombatesRol");
                });

            modelBuilder.Entity("AppGM.Core.TIRolMapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMapa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModeloMapaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeloRolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeloRolId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdMapa")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.HasIndex("ModeloMapaId");

                    b.HasIndex("ModeloRolId1");

                    b.ToTable("MapasRol");
                });

            modelBuilder.Entity("AppGM.Core.TIRolPersonaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPersonaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModeloPersonajeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeloRolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeloRolId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdPersonaje")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.HasIndex("ModeloPersonajeId");

                    b.HasIndex("ModeloRolId1");

                    b.ToTable("PersonajesRol");
                });

            modelBuilder.Entity("AppGM.Core.TIServantNoblePhantasm", b =>
                {
                    b.Property<int>("IdServant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdNoblePhantasm")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdServant", "IdNoblePhantasm");

                    b.HasIndex("IdNoblePhantasm");

                    b.ToTable("ServantNoblePhantasms");
                });

            modelBuilder.Entity("AppGM.Core.TISlotItem", b =>
                {
                    b.Property<int>("IdSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdSlot", "IdItem");

                    b.HasIndex("IdItem");

                    b.ToTable("TISlotItem");
                });

            modelBuilder.Entity("AppGM.Core.TIUnidadMapaVector2", b =>
                {
                    b.Property<int>("IdUnidadMapa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdVector")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUnidadMapa", "IdVector");

                    b.HasIndex("IdUnidadMapa")
                        .IsUnique();

                    b.HasIndex("IdVector");

                    b.ToTable("UnidadesMapaVectores2");
                });

            modelBuilder.Entity("AppGM.Core.TIUtilizableEfecto", b =>
                {
                    b.Property<int>("IdUtilizable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEfecto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUtilizable", "IdEfecto");

                    b.HasIndex("IdEfecto");

                    b.ToTable("TIUtilizableEfecto");
                });

            modelBuilder.Entity("AppGM.Core.TIUtilizableModificadorDeStatBase", b =>
                {
                    b.Property<int>("IdUtilizable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdModificadorStatBase")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUtilizable", "IdModificadorStatBase");

                    b.HasIndex("IdModificadorStatBase");

                    b.HasIndex("IdUtilizable")
                        .IsUnique();

                    b.ToTable("TIUtilizableModificadorDeStatBase");
                });

            modelBuilder.Entity("AppGM.Core.TIUtilizableTiradaBase", b =>
                {
                    b.Property<int>("IdUtilizable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTirada")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUtilizable", "IdTirada");

                    b.HasIndex("IdTirada");

                    b.HasIndex("IdUtilizable")
                        .IsUnique();

                    b.ToTable("TIUtilizableTiradaBase");
                });

            modelBuilder.Entity("AppGM.Core.ModeloMagia", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloHabilidad");

                    b.Property<bool>("EsParticular")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Nivel")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("AppGM.Core.ModeloNoblePhantasm", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloHabilidad");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("AppGM.Core.ModeloPerk", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloHabilidad");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("AppGM.Core.ModeloModificadorDeDefensa", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloModificadorDeStatBase");

                    b.Property<byte>("ModificacionFija")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ModificacionPorcentual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiposDeDaño")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("AppGM.Core.ModeloModificadorDeStatClase", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloModificadorDeStatBase");

                    b.Property<int>("IdObjeto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreClase")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("AppGM.Core.ModeloModificadorDeStatPrimitivos", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloModificadorDeStatBase");

                    b.Property<int>("StatsQueAfecta")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("AppGM.Core.ModeloInvocacion", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloPersonaje");

                    b.Property<bool>("EsAutomata")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("AppGM.Core.ModeloPersonajeJugable", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloPersonaje");

                    b.Property<int>("EClaseServant")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("RangoHechiceria")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("AppGM.Core.ModeloTiradaVariable", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloTiradaBase");

                    b.Property<ushort>("Caras")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Dados")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ModeloTiradaVariable");
                });

            modelBuilder.Entity("AppGM.Core.ModeloUnidadMapaMasterServant", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloUnidadMapa");

                    b.Property<int>("EClaseServant")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("AppGM.Core.ModeloItem", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloUtilizable");

                    b.Property<decimal>("SlotsQueOcupa")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("AppGM.Core.ModeloPortable", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloUtilizable");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("AppGM.Core.ModeloInvocacionCondicionada", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloInvocacion");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("AppGM.Core.ModeloInvocacionTemporal", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloInvocacion");

                    b.Property<byte>("TurnosDeDuracion")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("AppGM.Core.ModeloMaster", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloPersonajeJugable");

                    b.Property<string>("Afinidad")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Chr")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CommandSpells")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EBienestar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EClaseDeSuServant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lore")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Od")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OdActual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origen")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("VentajaChr")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("AppGM.Core.ModeloServant", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloPersonajeJugable");

                    b.Property<string>("Fuente")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PranaActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mERangoNP")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("AppGM.Core.ModeloTiradaDeDaño", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloTiradaVariable");

                    b.Property<int>("TipoDeDaño")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ModeloTiradaDeDaño");
                });

            modelBuilder.Entity("AppGM.Core.ModeloUnidadMapaInvocacionTrampa", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloUnidadMapaMasterServant");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsDeMaster")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Inicial")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("AppGM.Core.ModeloConsumible", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloItem");

                    b.Property<ushort>("Usos")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("UsosRestantes")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("AppGM.Core.ModeloDefensivo", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloPortable");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("AppGM.Core.ModeloOfensivo", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloPortable");

                    b.Property<int>("DañosQuePuedeInfligir")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("AppGM.Core.ModeloArmasDistancia", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloConsumible");

                    b.Property<int>("TipoDeDañoQueInflige")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("AppGM.Core.ModeloDefensivoAbsoluto", b =>
                {
                    b.HasBaseType("AppGM.Core.ModeloDefensivo");

                    b.Property<short>("Usos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ModeloDefensivoAbsoluto_Usos");

                    b.Property<short>("UsosRestantes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ModeloDefensivoAbsoluto_UsosRestantes");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("AppGM.Core.ModeloPersonaje", b =>
                {
                    b.HasOne("AppGM.Core.ModeloVector2", "Posicion")
                        .WithMany()
                        .HasForeignKey("PosicionId");

                    b.Navigation("Posicion");
                });

            modelBuilder.Entity("AppGM.Core.TIAdministradorDeCombateMapa", b =>
                {
                    b.HasOne("AppGM.Core.ModeloAdministradorDeCombate", "AdministradorDeCombate")
                        .WithMany("Mapas")
                        .HasForeignKey("IdAdministradorDeCombate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloMapa", "Mapa")
                        .WithMany()
                        .HasForeignKey("IdMapa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministradorDeCombate");

                    b.Navigation("Mapa");
                });

            modelBuilder.Entity("AppGM.Core.TIAdministradorDeCombateParticipante", b =>
                {
                    b.HasOne("AppGM.Core.ModeloAdministradorDeCombate", "AdministradorDeCombate")
                        .WithMany("Participantes")
                        .HasForeignKey("IdAdministradorDeCombate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloParticipante", "Participante")
                        .WithOne("CombateActual")
                        .HasForeignKey("AppGM.Core.TIAdministradorDeCombateParticipante", "IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministradorDeCombate");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("AppGM.Core.TIAlianzaContrato", b =>
                {
                    b.HasOne("AppGM.Core.ModeloAlianza", "Alianza")
                        .WithOne("ContratoDeAlianza")
                        .HasForeignKey("AppGM.Core.TIAlianzaContrato", "IdAlianza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloContrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alianza");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("AppGM.Core.TIArmasDistanciaEfecto", b =>
                {
                    b.HasOne("AppGM.Core.ModeloArmasDistancia", "ArmasDistancia")
                        .WithMany("EfectoQueInflige")
                        .HasForeignKey("IdArmasDistancia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloEfecto", "Efecto")
                        .WithMany()
                        .HasForeignKey("IdEfecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmasDistancia");

                    b.Navigation("Efecto");
                });

            modelBuilder.Entity("AppGM.Core.TIArmasDistanciaTiradaDeDaño", b =>
                {
                    b.HasOne("AppGM.Core.ModeloArmasDistancia", "ArmasDistancia")
                        .WithOne("TiradaDeDaño")
                        .HasForeignKey("AppGM.Core.TIArmasDistanciaTiradaDeDaño", "IdArmasDistancia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloTiradaDeDaño", "TiradaDaño")
                        .WithMany()
                        .HasForeignKey("IdTirada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmasDistancia");

                    b.Navigation("TiradaDaño");
                });

            modelBuilder.Entity("AppGM.Core.TIArmasDistanciaTiradaVariable", b =>
                {
                    b.HasOne("AppGM.Core.ModeloArmasDistancia", "ArmasDistancia")
                        .WithOne("TiradaRafaga")
                        .HasForeignKey("AppGM.Core.TIArmasDistanciaTiradaVariable", "IdArmasDistancia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloTiradaVariable", "TiradaVariable")
                        .WithMany()
                        .HasForeignKey("IdTirada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmasDistancia");

                    b.Navigation("TiradaVariable");
                });

            modelBuilder.Entity("AppGM.Core.TIEfectoModificadorDeStatBase", b =>
                {
                    b.HasOne("AppGM.Core.ModeloEfecto", "Efecto")
                        .WithMany("Modificaciones")
                        .HasForeignKey("IdEfecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloModificadorDeStatBase", "Modificador")
                        .WithMany()
                        .HasForeignKey("IdModificadorDeStat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Efecto");

                    b.Navigation("Modificador");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadCargasHabilidad", b =>
                {
                    b.HasOne("AppGM.Core.ModeloCargas", "ModeloCargas")
                        .WithMany()
                        .HasForeignKey("IdCargasHabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloHabilidad", "Habilidad")
                        .WithOne("CargasHabilidad")
                        .HasForeignKey("AppGM.Core.TIHabilidadCargasHabilidad", "IdHabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("ModeloCargas");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadEfecto", b =>
                {
                    b.HasOne("AppGM.Core.ModeloEfecto", "Efecto")
                        .WithMany()
                        .HasForeignKey("IdEfecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloHabilidad", "Habilidad")
                        .WithMany("EfectosSobreUsuarioEfectoSobreObjetivo")
                        .HasForeignKey("IdHabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Efecto");

                    b.Navigation("Habilidad");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadInvocacion", b =>
                {
                    b.HasOne("AppGM.Core.ModeloHabilidad", "Habilidad")
                        .WithMany("Invocacion")
                        .HasForeignKey("IdHabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloInvocacion", "Invocacion")
                        .WithMany()
                        .HasForeignKey("IdInvocacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("Invocacion");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadItem", b =>
                {
                    b.HasOne("AppGM.Core.ModeloHabilidad", "Habilidad")
                        .WithMany("ItemsQueCuestaItemInvocacion")
                        .HasForeignKey("IdHabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloItem", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadLimitador", b =>
                {
                    b.HasOne("AppGM.Core.ModeloHabilidad", "Habilidad")
                        .WithOne("LimiteDeUsos")
                        .HasForeignKey("AppGM.Core.TIHabilidadLimitador", "IdHabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloLimitador", "ModeloLimitador")
                        .WithMany()
                        .HasForeignKey("IdLimitador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("ModeloLimitador");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadTiradaBase", b =>
                {
                    b.HasOne("AppGM.Core.ModeloHabilidad", "Habilidad")
                        .WithMany("TiradasDeUso")
                        .HasForeignKey("IdHabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloTiradaBase", "TiradaBase")
                        .WithMany()
                        .HasForeignKey("IdTirada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("TiradaBase");
                });

            modelBuilder.Entity("AppGM.Core.TIHabilidadTiradaDeDaño", b =>
                {
                    b.HasOne("AppGM.Core.ModeloHabilidad", "Habilidad")
                        .WithOne("TiradaDeDaño")
                        .HasForeignKey("AppGM.Core.TIHabilidadTiradaDeDaño", "IdHabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloTiradaDeDaño", "TiradaDeDaño")
                        .WithMany()
                        .HasForeignKey("IdTirada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("TiradaDeDaño");
                });

            modelBuilder.Entity("AppGM.Core.TIInvocacionDatosInvocacion", b =>
                {
                    b.HasOne("AppGM.Core.ModeloDatosInvocacionBase", "DatosInvocacion")
                        .WithMany()
                        .HasForeignKey("IdDatos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloInvocacion", "Invocacion")
                        .WithOne("DatosInvocacion")
                        .HasForeignKey("AppGM.Core.TIInvocacionDatosInvocacion", "IdInvocacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatosInvocacion");

                    b.Navigation("Invocacion");
                });

            modelBuilder.Entity("AppGM.Core.TIInvocacionEfecto", b =>
                {
                    b.HasOne("AppGM.Core.ModeloEfecto", "Efecto")
                        .WithMany()
                        .HasForeignKey("IdEfecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloInvocacion", "Invocacion")
                        .WithOne("Efecto")
                        .HasForeignKey("AppGM.Core.TIInvocacionEfecto", "IdInvocacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Efecto");

                    b.Navigation("Invocacion");
                });

            modelBuilder.Entity("AppGM.Core.TIInvocacionPersonaje", b =>
                {
                    b.HasOne("AppGM.Core.ModeloInvocacion", "Invocacion")
                        .WithOne("Invocador")
                        .HasForeignKey("AppGM.Core.TIInvocacionPersonaje", "IdInvocacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "PersonajeInvocador")
                        .WithMany()
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invocacion");

                    b.Navigation("PersonajeInvocador");
                });

            modelBuilder.Entity("AppGM.Core.TIMapaUnidadMapa", b =>
                {
                    b.HasOne("AppGM.Core.ModeloMapa", "Mapa")
                        .WithMany("PosicionesUnidades")
                        .HasForeignKey("IdMapa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloUnidadMapa", "Unidad")
                        .WithMany()
                        .HasForeignKey("IdUnidadMapa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapa");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("AppGM.Core.TIModificadorDeStatBaseTiradaBase", b =>
                {
                    b.HasOne("AppGM.Core.ModeloModificadorDeStatBase", "ModificadorDeStatBase")
                        .WithOne("ValorTirada")
                        .HasForeignKey("AppGM.Core.TIModificadorDeStatBaseTiradaBase", "IdModificadorDeStatBase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloTiradaBase", "TiradaBase")
                        .WithMany()
                        .HasForeignKey("IdTirada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModificadorDeStatBase");

                    b.Navigation("TiradaBase");
                });

            modelBuilder.Entity("AppGM.Core.TIOfensivoEfecto", b =>
                {
                    b.HasOne("AppGM.Core.ModeloEfecto", "Efecto")
                        .WithMany()
                        .HasForeignKey("IdEfecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloOfensivo", "Ofensivo")
                        .WithOne("EfectoQueInflige")
                        .HasForeignKey("AppGM.Core.TIOfensivoEfecto", "IdOfensivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Efecto");

                    b.Navigation("Ofensivo");
                });

            modelBuilder.Entity("AppGM.Core.TIOfensivoTiradaDeDaño", b =>
                {
                    b.HasOne("AppGM.Core.ModeloOfensivo", "Ofensivo")
                        .WithMany("TiradasDeDaño")
                        .HasForeignKey("IdOfensivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloTiradaDeDaño", "TiradaDeDaño")
                        .WithMany()
                        .HasForeignKey("IdTiradaDeDaño")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ofensivo");

                    b.Navigation("TiradaDeDaño");
                });

            modelBuilder.Entity("AppGM.Core.TIParticipanteAccion", b =>
                {
                    b.HasOne("AppGM.Core.ModeloAccion", "Accion")
                        .WithMany()
                        .HasForeignKey("IdAccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloParticipante", "Participante")
                        .WithMany("AccionesRealizadas")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accion");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("AppGM.Core.TIParticipantePersonaje", b =>
                {
                    b.HasOne("AppGM.Core.ModeloParticipante", "Participante")
                        .WithOne("Personaje")
                        .HasForeignKey("AppGM.Core.TIParticipantePersonaje", "IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("ParticipacionEnCombates")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeAlianza", b =>
                {
                    b.HasOne("AppGM.Core.ModeloAlianza", "Alianza")
                        .WithMany("PersonajesAfectados")
                        .HasForeignKey("IdAlianza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("Alianzas")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alianza");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeArmaDistancia", b =>
                {
                    b.HasOne("AppGM.Core.ModeloArmasDistancia", "ArmaDistancia")
                        .WithMany()
                        .HasForeignKey("IdArmaDistancia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("ArmasDistancia")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmaDistancia");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeContrato", b =>
                {
                    b.HasOne("AppGM.Core.ModeloContrato", "Contrato")
                        .WithMany("PersonajesAfectados")
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("Contratos")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeDefensivo", b =>
                {
                    b.HasOne("AppGM.Core.ModeloDefensivo", "Defensivo")
                        .WithMany()
                        .HasForeignKey("IdDefensivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("Armadura")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defensivo");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeEfecto", b =>
                {
                    b.HasOne("AppGM.Core.ModeloEfecto", "Efecto")
                        .WithMany()
                        .HasForeignKey("IdEfecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("Efectos")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Efecto");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeHabilidad", b =>
                {
                    b.HasOne("AppGM.Core.ModeloHabilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("IdHabilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("Skills")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeJugableCaracteristicas", b =>
                {
                    b.HasOne("AppGM.Core.ModeloCaracteristicas", "Caracteristicas")
                        .WithMany()
                        .HasForeignKey("IdCaracteristica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonajeJugable", "PersonajeJugable")
                        .WithOne("Caracteristicas")
                        .HasForeignKey("AppGM.Core.TIPersonajeJugableCaracteristicas", "IdPersonajeJugable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristicas");

                    b.Navigation("PersonajeJugable");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeJugableInvocacion", b =>
                {
                    b.HasOne("AppGM.Core.ModeloInvocacion", "Invocacion")
                        .WithMany()
                        .HasForeignKey("IdInvocacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonajeJugable", "PersonajeJugable")
                        .WithMany("Invocaciones")
                        .HasForeignKey("IdPersonajeJugable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invocacion");

                    b.Navigation("PersonajeJugable");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeMagia", b =>
                {
                    b.HasOne("AppGM.Core.ModeloMagia", "Magia")
                        .WithMany()
                        .HasForeignKey("IdMagia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("Magias")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magia");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeModificadorDeDefensa", b =>
                {
                    b.HasOne("AppGM.Core.ModeloModificadorDeDefensa", "ModificadorDeDefensa")
                        .WithMany()
                        .HasForeignKey("IdModificadorDefensa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("ModificadoresDeDefensa")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModificadorDeDefensa");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajePerk", b =>
                {
                    b.HasOne("AppGM.Core.ModeloPerk", "Perk")
                        .WithMany()
                        .HasForeignKey("IdPerk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("Perks")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perk");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeUnidadMapa", b =>
                {
                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany()
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloUnidadMapa", "Unidad")
                        .WithOne("Personaje")
                        .HasForeignKey("AppGM.Core.TIPersonajeUnidadMapa", "IdUnidadMapa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("AppGM.Core.TIPersonajeUtilizable", b =>
                {
                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithMany("Inventario")
                        .HasForeignKey("IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloUtilizable", "Utilizable")
                        .WithMany()
                        .HasForeignKey("IdUtilizable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");

                    b.Navigation("Utilizable");
                });

            modelBuilder.Entity("AppGM.Core.TIPortableModificadorDeStatBase", b =>
                {
                    b.HasOne("AppGM.Core.ModeloModificadorDeStatBase", "Modificador")
                        .WithMany()
                        .HasForeignKey("IdModificadorDeStat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPortable", "Portable")
                        .WithMany("VentajasYDesventajasDeEquiparlo")
                        .HasForeignKey("IdPortable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modificador");

                    b.Navigation("Portable");
                });

            modelBuilder.Entity("AppGM.Core.TIPortableSlots", b =>
                {
                    b.HasOne("AppGM.Core.ModeloPortable", "Portable")
                        .WithMany("Slots")
                        .HasForeignKey("IdPortable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("IdSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portable");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("AppGM.Core.TIRolCombate", b =>
                {
                    b.HasOne("AppGM.Core.ModeloAdministradorDeCombate", "Combate")
                        .WithOne("RolCombate")
                        .HasForeignKey("AppGM.Core.TIRolCombate", "IdCombate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloRol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloAdministradorDeCombate", null)
                        .WithMany()
                        .HasForeignKey("ModeloAdministradorDeCombateId");

                    b.HasOne("AppGM.Core.ModeloRol", null)
                        .WithMany("Combates")
                        .HasForeignKey("ModeloRolId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combate");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AppGM.Core.TIRolMapa", b =>
                {
                    b.HasOne("AppGM.Core.ModeloMapa", "Mapa")
                        .WithOne("RolMapa")
                        .HasForeignKey("AppGM.Core.TIRolMapa", "IdMapa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloRol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloMapa", null)
                        .WithMany()
                        .HasForeignKey("ModeloMapaId");

                    b.HasOne("AppGM.Core.ModeloRol", null)
                        .WithMany("Mapas")
                        .HasForeignKey("ModeloRolId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AppGM.Core.TIRolPersonaje", b =>
                {
                    b.HasOne("AppGM.Core.ModeloPersonaje", "Personaje")
                        .WithOne("RolPersonaje")
                        .HasForeignKey("AppGM.Core.TIRolPersonaje", "IdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloRol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloPersonaje", null)
                        .WithMany()
                        .HasForeignKey("ModeloPersonajeId");

                    b.HasOne("AppGM.Core.ModeloRol", null)
                        .WithMany("Personajes")
                        .HasForeignKey("ModeloRolId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AppGM.Core.TIServantNoblePhantasm", b =>
                {
                    b.HasOne("AppGM.Core.ModeloNoblePhantasm", "NoblePhantasm")
                        .WithMany()
                        .HasForeignKey("IdNoblePhantasm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloServant", "Servant")
                        .WithMany("NoblePhantasms")
                        .HasForeignKey("IdServant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoblePhantasm");

                    b.Navigation("Servant");
                });

            modelBuilder.Entity("AppGM.Core.TISlotItem", b =>
                {
                    b.HasOne("AppGM.Core.ModeloItem", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloSlot", "Slot")
                        .WithMany("ItemsAlmacenados")
                        .HasForeignKey("IdSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("AppGM.Core.TIUnidadMapaVector2", b =>
                {
                    b.HasOne("AppGM.Core.ModeloUnidadMapa", "Unidad")
                        .WithOne("Posicion")
                        .HasForeignKey("AppGM.Core.TIUnidadMapaVector2", "IdUnidadMapa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloVector2", "Posicion")
                        .WithMany()
                        .HasForeignKey("IdVector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posicion");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("AppGM.Core.TIUtilizableEfecto", b =>
                {
                    b.HasOne("AppGM.Core.ModeloEfecto", "Efecto")
                        .WithMany()
                        .HasForeignKey("IdEfecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloUtilizable", "Utilizable")
                        .WithMany("EfectoSobreUsuarioYObjetivo")
                        .HasForeignKey("IdUtilizable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Efecto");

                    b.Navigation("Utilizable");
                });

            modelBuilder.Entity("AppGM.Core.TIUtilizableModificadorDeStatBase", b =>
                {
                    b.HasOne("AppGM.Core.ModeloModificadorDeStatBase", "ModificadorDeStatBase")
                        .WithMany()
                        .HasForeignKey("IdModificadorStatBase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloUtilizable", "Utilizable")
                        .WithOne("VentajaAlUtilizarlo")
                        .HasForeignKey("AppGM.Core.TIUtilizableModificadorDeStatBase", "IdUtilizable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModificadorDeStatBase");

                    b.Navigation("Utilizable");
                });

            modelBuilder.Entity("AppGM.Core.TIUtilizableTiradaBase", b =>
                {
                    b.HasOne("AppGM.Core.ModeloTiradaBase", "TiradaBase")
                        .WithMany()
                        .HasForeignKey("IdTirada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGM.Core.ModeloUtilizable", "Utilizable")
                        .WithOne("TiradaDeUso")
                        .HasForeignKey("AppGM.Core.TIUtilizableTiradaBase", "IdUtilizable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TiradaBase");

                    b.Navigation("Utilizable");
                });

            modelBuilder.Entity("AppGM.Core.ModeloAdministradorDeCombate", b =>
                {
                    b.Navigation("Mapas");

                    b.Navigation("Participantes");

                    b.Navigation("RolCombate");
                });

            modelBuilder.Entity("AppGM.Core.ModeloAlianza", b =>
                {
                    b.Navigation("ContratoDeAlianza");

                    b.Navigation("PersonajesAfectados");
                });

            modelBuilder.Entity("AppGM.Core.ModeloContrato", b =>
                {
                    b.Navigation("PersonajesAfectados");
                });

            modelBuilder.Entity("AppGM.Core.ModeloEfecto", b =>
                {
                    b.Navigation("Modificaciones");
                });

            modelBuilder.Entity("AppGM.Core.ModeloHabilidad", b =>
                {
                    b.Navigation("CargasHabilidad");

                    b.Navigation("EfectosSobreUsuarioEfectoSobreObjetivo");

                    b.Navigation("Invocacion");

                    b.Navigation("ItemsQueCuestaItemInvocacion");

                    b.Navigation("LimiteDeUsos");

                    b.Navigation("TiradaDeDaño");

                    b.Navigation("TiradasDeUso");
                });

            modelBuilder.Entity("AppGM.Core.ModeloMapa", b =>
                {
                    b.Navigation("PosicionesUnidades");

                    b.Navigation("RolMapa");
                });

            modelBuilder.Entity("AppGM.Core.ModeloModificadorDeStatBase", b =>
                {
                    b.Navigation("ValorTirada");
                });

            modelBuilder.Entity("AppGM.Core.ModeloParticipante", b =>
                {
                    b.Navigation("AccionesRealizadas");

                    b.Navigation("CombateActual");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("AppGM.Core.ModeloPersonaje", b =>
                {
                    b.Navigation("Alianzas");

                    b.Navigation("Armadura");

                    b.Navigation("ArmasDistancia");

                    b.Navigation("Contratos");

                    b.Navigation("Efectos");

                    b.Navigation("Inventario");

                    b.Navigation("Magias");

                    b.Navigation("ModificadoresDeDefensa");

                    b.Navigation("ParticipacionEnCombates");

                    b.Navigation("Perks");

                    b.Navigation("RolPersonaje");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("AppGM.Core.ModeloRol", b =>
                {
                    b.Navigation("Combates");

                    b.Navigation("Mapas");

                    b.Navigation("Personajes");
                });

            modelBuilder.Entity("AppGM.Core.ModeloSlot", b =>
                {
                    b.Navigation("ItemsAlmacenados");
                });

            modelBuilder.Entity("AppGM.Core.ModeloUnidadMapa", b =>
                {
                    b.Navigation("Personaje");

                    b.Navigation("Posicion");
                });

            modelBuilder.Entity("AppGM.Core.ModeloUtilizable", b =>
                {
                    b.Navigation("EfectoSobreUsuarioYObjetivo");

                    b.Navigation("TiradaDeUso");

                    b.Navigation("VentajaAlUtilizarlo");
                });

            modelBuilder.Entity("AppGM.Core.ModeloInvocacion", b =>
                {
                    b.Navigation("DatosInvocacion");

                    b.Navigation("Efecto");

                    b.Navigation("Invocador");
                });

            modelBuilder.Entity("AppGM.Core.ModeloPersonajeJugable", b =>
                {
                    b.Navigation("Caracteristicas");

                    b.Navigation("Invocaciones");
                });

            modelBuilder.Entity("AppGM.Core.ModeloPortable", b =>
                {
                    b.Navigation("Slots");

                    b.Navigation("VentajasYDesventajasDeEquiparlo");
                });

            modelBuilder.Entity("AppGM.Core.ModeloServant", b =>
                {
                    b.Navigation("NoblePhantasms");
                });

            modelBuilder.Entity("AppGM.Core.ModeloOfensivo", b =>
                {
                    b.Navigation("EfectoQueInflige");

                    b.Navigation("TiradasDeDaño");
                });

            modelBuilder.Entity("AppGM.Core.ModeloArmasDistancia", b =>
                {
                    b.Navigation("EfectoQueInflige");

                    b.Navigation("TiradaDeDaño");

                    b.Navigation("TiradaRafaga");
                });
#pragma warning restore 612, 618
        }
    }
}
